### ISSUE TITLE
issues when running with Beaglebone Black

### ISSUE THREAD

**Issue by sydneykcho** [adafruit/Adafruit_Python_SSD1306#30]
when I tried to run the programs with both pythion 2 and 3, an error msg showed as below:

root@beaglebone:~/Adafruit_Python_SSD1306/examples# python image.py
Traceback (most recent call last):
  File "image.py", line 56, in <module>
    disp.begin()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 148, in begin
    self._initialize()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 247, in _initialize
    self.command(SSD1306_DISPLAYOFF)                    # 0xAE
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 129, in command
    self._i2c.write8(control, c)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO-1.0.3-py2.7.egg/Adafruit_GPIO/I2C.py", line 116, in write8
    self._bus.write_byte_data(self._address, register, value)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
    self._device.write(data)
IOError: [Errno 16] Device or resource busy

Did I get something wrong in the program?
Regards,

**Comment by ladyada** [comment]
hiya, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring
