### ISSUE TITLE
IOError: [Errno 6] No such device or address

### ISSUE THREAD

**Issue by NirajSudhirMehta** [adafruit/Adafruit_Python_SSD1306#32]
Hardware : Orange Pi Zero

OS : ARMBIAN 5.73 stable Debian GNU/Linux 9 (stretch) 4.19.20-sunxi

Python : Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2

sudo i2cdetect -y 0
0 1 2 3 4 5 6 7 8 9 a b c d e f
00: -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.

import Adafruit_GPIO.SPI as SPI
import Adafruit_SSD1306

from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

RST = None

disp = Adafruit_SSD1306.SSD1306_128_64(rst=RST, i2c_address=0x3C)

disp.begin()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 148, in begin self._initialize()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 247, in _initialize self.command(SSD1306_DISPLAYOFF)                    # 0xAE
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 129, in command self._i2c.write8(control, c)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO/I2C.py", line 114, in write8 self._bus.write_byte_data(self._address, register, value)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
    self._device.write(data)
IOError: [Errno 6] No such device or address

**Comment by ladyada** [comment]
hiya, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring
