### ISSUE TITLE
IOError: [Errno 70] Communication error on send

### ISSUE THREAD

**Issue by wky0211** [adafruit/Adafruit_Python_SSD1306#37]
Hardware: Orange PI Zero
OS: Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
Python  version: 2.7.12-1~16.04

root@OrangePI:~/Adafruit_Python_SSD1306/examples# sudo i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

root@OrangePI:~/Adafruit_Python_SSD1306/examples# python stats.py
Traceback (most recent call last):
  File "stats.py", line 71, in <module>
    disp.begin()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 148, in begin
    self._initialize()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 292, in _initialize
    self.command(SSD1306_DISPLAYOFF)                    # 0xAE
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 129, in command
    self._i2c.write8(control, c)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO/I2C.py", line 114, in write8
    self._bus.write_byte_data(self._address, register, value)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
    self._device.write(data)
IOError: [Errno 70] Communication error on send

**Comment by ladyada** [comment]
hiya, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring
